version: '3.8'

services:
  my-business-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    networks:
      - my-business-network

networks:
  my-business-network:
    driver: bridge